version: '3.7'

services:
  customer-service:
    container_name: customer-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass Customer-Service-Redis
    ports:
      - "6379:6379"


  mongo-express:
    deploy:
      replicas: 0
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb_data: